blank_issues_enabled: false
contact_links:
  - name: "â“ Ask a Question"
    url: https://github.com/DeebotUniverse/client.py/discussions/new
    about: For asking a question please select the category "Q&A"
  - name: "ğŸ’¡ Suggest an feature/idea"
    url: https://github.com/DeebotUniverse/client.py/discussions/new
    about: For feature request please select the category "Ideas"
